# Generated by Django 4.2.2 on 2023-08-19 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraperapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='links',
            old_name='adress',
            new_name='address',
        ),
    ]
